### ISSUE TITLE
Lots of Issues

### ISSUE THREAD

**Issue by Shrekfied** [JaydenDev/Ink-Desktop#1]
1. Its just a blank white screen.
2. The show/hide right click menus give me errors.
3. There should be a custom icon instead of the default Electron one.

BTW, I'm using the v0.3.1 amd64 Debian release on Ubuntu.

**Comment by jdev082** [comment]
3. The custom icon works on Windows, it not working on Linux may be due to an incomplatible icon format.
2. How did you access it when the app was broken?
1. I will fix that soon
^ I don't have time right now, I'll fix it tomorrow.

**Comment by jdev082** [comment]
Blank screen issue fixed, the rest will be fixed tomorrow.

**Comment by Shrekfied** [comment]
>     4. How did you access it when the app was broken?
I just right clicked on the window.
![Screenshot from 2022-06-16 23-50-57](https://user-images.githubusercontent.com/104044615/174221601-f141a844-fa88-4bab-af7e-3bb07310265b.png)

**Comment by jdev082** [comment]
I completely forgot about a feature in the app _I_ wrote. Alright, so the white screen should be fixed. I'll test it and compile a new poitn release.

**Comment by jdev082** [comment]
All the issues in the software have been fixed, the fixes are bundled in the latest v0.3.2 release.

**Comment by Shrekfied** [comment]
> the fixes are bundled in the latest v0.3.2 release.

Can you release it on GitHub, so that I can test it?

**Comment by jdev082** [comment]
@dinonull done!
